Repository aufsprit/FC-project-board, pull requests merged in 2022-08, with the labels that each got.

#5 게시판 서비스 유즈케이스 작성
  use-case.svg
  제목 없는 다이어그램.drawio
Labels: documentation

#7 스프링 부트 프로젝트 시작하기
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/fc/projectboard/FcProjectBoardApplication.java
  src/main/resources/application.properties
  src/test/java/com/fc/projectboard/FcProjectBoardApplicationTests.java
Labels: documentation

#9 도메인 설계하기
  documents/project_board_erd.svg
  src/main/java/com/fc/projectboard/domain/Article.java
  src/main/java/com/fc/projectboard/domain/ArticleComment.java
Labels: documentation, enhancement

#11 데이터베이스 접근 로직 테스트 정의
  build.gradle
  documents/project_board_erd.svg
  src/main/java/com/fc/projectboard/config/JpaConfig.java
  src/main/java/com/fc/projectboard/domain/Article.java
  src/main/java/com/fc/projectboard/domain/ArticleComment.java
  src/main/java/com/fc/projectboard/repository/ArticleCommentRepository.java
  src/main/java/com/fc/projectboard/repository/ArticleRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/main/resources/data.sql
  src/test/java/com/fc/projectboard/repository/JpaRepositoryTest.java
Labels: documentation, enhancement

#13 데이터베이스 접근 로직 구현
  src/main/java/com/fc/projectboard/domain/Article.java
  src/main/java/com/fc/projectboard/domain/ArticleComment.java
  src/main/java/com/fc/projectboard/domain/AuditingFields.java
  src/main/resources/application.yaml
Labels: enhancement

#14 게시판 api 만들기 - data REST 적용 및 테스트 정의
  build.gradle
  src/main/java/com/fc/projectboard/repository/ArticleCommentRepository.java
  src/main/java/com/fc/projectboard/repository/ArticleRepository.java
  src/main/resources/META-INF/additional-spring-configuration-metadata.json
  src/main/resources/application.yaml
  src/main/resources/data.sql
  src/test/java/com/fc/projectboard/controller/DataRestTest.java
Labels: enhancement

#15 게시판 api 만들기 - 구현까지 완료
  .gitignore
  build.gradle
  src/main/java/com/fc/projectboard/repository/ArticleCommentRepository.java
  src/main/java/com/fc/projectboard/repository/ArticleRepository.java
  src/test/java/com/fc/projectboard/controller/DataRestTest.java
Labels: enhancement

#17 게시판 서비스 뷰 만들기
  build.gradle
  src/main/java/com/fc/projectboard/FcProjectBoardApplication.java
  src/main/java/com/fc/projectboard/config/SecurityConfig.java
  src/main/java/com/fc/projectboard/config/ThymeleafConfig.java
  src/main/java/com/fc/projectboard/controller/ArticleController.java
  src/main/resources/application.yaml
  src/main/resources/static/css/search-bar.css
  src/main/resources/templates/articles/detail.html
  src/main/resources/templates/articles/detail.th.xml
  src/main/resources/templates/articles/index.html
  src/main/resources/templates/articles/index.th.xml
  src/main/resources/templates/footer.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/test/java/com/fc/projectboard/controller/ArticleControllerTest.java
  src/test/java/com/fc/projectboard/controller/AuthController.java
Labels: enhancement
